### ISSUE TITLE
Dat mirror

### ISSUE THREAD

**Issue by millette** [lorey/top-regional-repositories#1]
The [Dat Project](https://datproject.org/) makes it very easy to share large datasets over P2P.

I've taken the liberty to host a dat:

* dat://839dd3e4f0620b6c70eb2fb2574878eb68e7cd50a729f8b9fe51ba1ee34664d0/
* dat://top-regional-repositories-millette.hashbase.io
* https://top-regional-repositories-millette.hashbase.io
 
For now, I'm just pulling from git once in a while, and the dat gets updated simultaneously. I will probably automate this, unless you prefer to create the dat yourself.

*This is a follow-up to [HN](https://news.ycombinator.com/item?id=14581644)*

**Comment by lorey** [comment]
Okay, thanks. I'm cool with dat (pun intended), although I don't see the benefit with less than 1MB right now. We can think about including it if we automate the builds :+1: Thanks for the follow-up.

**Comment by millette** [comment]
Very true, 1 MiB... but it could grow larger, many cities out there :-)

Good luck with your project.
